### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by Xinjiann** [Blueprintf/pointlstm-gesture-recognition-pytorch#1]
Hi @Blueprintf,

When I ran the training step by "python main.py --phase=train --device=0 ", there was an error  "No such file or directory: './work_dir/pointlstm/epoch200_model.pt'", I observed that it's due to the definition of weight in pointlstm.yaml, do you know how to deal with it?

Thanks

**Comment by Blueprintf** [comment]
I forget to comment the checkpoint in the config file, you can comment L12 of ./experiments/pointlstm.yaml
"# weights: ./work_dir/pointlstm/epoch200_model.pt" and try to run the training command again.

Sorry for this problem.
