### ISSUE TITLE
Testing on CPU

### ISSUE THREAD

**Issue by shravanchndr** [Blueprintf/pointlstm-gesture-recognition-pytorch#3]
Hi, @Blueprintf 

Can you please list out the changes that are required when testing the model on a CPU? 

Thank you!

**Comment by Blueprintf** [comment]
You can set device in pointlstm.yaml as empty, for example: 
# device: 1
device:  
More details can be found in ./experiments/utils/device.py

**Comment by shravanchndr** [comment]
Okay. Will try. Thank you so much!
