### ISSUE TITLE
Could you please share the script to process NVGesture dataset?

### ISSUE THREAD

**Issue by happyCodingSusan** [Blueprintf/pointlstm-gesture-recognition-pytorch#4]
@Blueprintf , great work. Very impressive! Thanks for sharing the code.

In your paper, you showed very good performance on NVGesture dataset. I wonder how you pre-process NVGesture  dataset which does not have ground truth for hand regions. Could you please share the pre-processing code for NVGesture  dataset (similar to shrec17_process.py).

Many thanks.

**Comment by Blueprintf** [comment]
We simply use the Otsu threshold (cv2.threshold) to remove the background and then sample points from hand regions. I will upload the pre-processing script later, perhaps this weekend. You can find details about it in our supplementary material.

**Comment by happyCodingSusan** [comment]
@Blueprintf, thanks for your fast reply. I will wait for your script.

**Comment by ycmin95** [comment]
NVGesture relevant scripts have been uploaded.

**Comment by happyCodingSusan** [comment]
Thanks, @Blueprintf , I will test it.
